In [1]:
import pandas as pd

print('initial data:')
df = pd.read_csv('harvest_report.csv', index_col=0)
print(df)
df.info()

initial data:
         Date Block_ID Harvester  Total_Weight_kg  Rotten_Bunches
0  2024-01-20   Blok A      Budi             1200               5
1  2024-01-20   Blok B    Slamet              850               2
2  2024-01-20   Blok A      Joko             1300               8
3  2024-01-21   Blok C    Slamet              900               1
4  2024-01-21   Blok B      Budi             1150               4
5  2024-01-22   Blok A      Joko             1250               3
6  2024-01-22   Blok C      Budi              980               2
7  2024-01-22   Blok A       NaN             1100               5
<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             8 non-null      object
 1   Block_ID         8 non-null      object
 2   Harvester        7 non-null      object
 3   Total_Weight_kg  8 non-null      int64
 4   Rotten_Bunches   8 non-null      int64
dtypes: int64(2), object(3)
memory usage: 384.0+ bytes

In [2]:
# Kalau mau otomatis ngisi semua kolom teks yang kosong sebelum diubah jadi kategori:
# 1. Ambil semua kolom object
cols_object = df.select_dtypes(include=['object']).columns

# 2. Isi yang kosong dengan 'Missing' lalu ubah ke category
for col in cols_object:
    df[col] = df[col].fillna('Unknown').astype('category')

# 3. Untuk kolom angka, isi dengan 0 Hajar semua jenis angka (int & float)
cols_numeric = df.select_dtypes(include=['number']).columns
df[cols_numeric] = df[cols_numeric].fillna(0)

# 4. Konversi Tanggal (Manual karena formatnya spesifik)
if 'Date' in df.columns:
    df['Date'] = pd.to_datetime(df['Date'])


print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             8 non-null      datetime64[ns]
 1   Block_ID         8 non-null      category
 2   Harvester        8 non-null      category
 3   Total_Weight_kg  8 non-null      int64
 4   Rotten_Bunches   8 non-null      int64
dtypes: category(2), datetime64[ns](1), int64(2)
memory usage: 608.0 bytes
None

**Kamu harus isi fillna() dulu baru astype('category'). Kalau sudah jadi kategori, nambahin nilai baru yang belum terdaftar di "kategori" itu bisa bikin error atau ribet menurut dokumentasi Pandas Fillna.**

In [3]:
df

        Date Block_ID Harvester  Total_Weight_kg  Rotten_Bunches
0 2024-01-20   Blok A      Budi             1200               5
1 2024-01-20   Blok B    Slamet              850               2
2 2024-01-20   Blok A      Joko             1300               8
3 2024-01-21   Blok C    Slamet              900               1
4 2024-01-21   Blok B      Budi             1150               4
5 2024-01-22   Blok A      Joko             1250               3
6 2024-01-22   Blok C      Budi              980               2
7 2024-01-22   Blok A   Unknown             1100               5

In [4]:
# # CHEAT SHEET

# import pandas as pd

# # 1. Load Data & Beresin Index 'Sampah'
# # Pakai index_col=0 biar kolom 'Unnamed: 0' nggak muncul
# df = pd.read_csv('harvest_report.csv', index_col=0)

# # 2. Hajar Otomatis Kolom Teks (Object -> Category)
# # Best Practice: Hemat RAM & cocok buat data berulang (Blok, Nama, dsb)
# for col in df.select_dtypes(include=['object']).columns:
#     df[col] = df[col].fillna('Missing').astype('category')

# # 3. Hajar Otomatis Kolom Angka (Int/Float -> Number)
# # Pakai 'number' buat nangkep semua tipe angka sekaligus
# for col in df.select_dtypes(include=['number']).columns:
#     df[col] = df[col].fillna(0)

# # 4. Konversi Tanggal (Manual karena formatnya spesifik)
# if 'Date' in df.columns:
#     df['Date'] = pd.to_datetime(df['Date'])

# # 5. Cek Hasil Akhir
# print(df.info())

In [5]:
# df['Date'] = pd.to_datetime(df['Date'])
# df['Block_ID'] = df['Block_ID'].astype('category')
# df.info()

In [6]:
# # ganti tipe data pake dictionary jika kolomnya beda-beda tipe

# # Tentukan kolom dan tipe datanya
# convert_dict = {
#     'Date': 'datetime64[ns]',
#     'Block_ID': 'category',
#     'Harvester': 'category' # Contoh tambah kolom lain
# }

# df = df.astype(convert_dict)
# df.info()

In [7]:
# pakai looping kalau mau hajar semua kolom teks jadi kategori secara otomatis
# Ambil semua kolom yang tipenya object/string, lalu ubah ke category
for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].astype('category')

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             8 non-null      datetime64[ns]
 1   Block_ID         8 non-null      category
 2   Harvester        8 non-null      category
 3   Total_Weight_kg  8 non-null      int64
 4   Rotten_Bunches   8 non-null      int64
dtypes: category(2), datetime64[ns](1), int64(2)
memory usage: 608.0 bytes

In [8]:
print(df.isna().sum())

Date               0
Block_ID           0
Harvester          0
Total_Weight_kg    0
Rotten_Bunches     0
dtype: int64

In [13]:
df.head()

        Date Block_ID Harvester  Total_Weight_kg  Rotten_Bunches
0 2024-01-20   Blok A      Budi             1200               5
1 2024-01-20   Blok B    Slamet              850               2
2 2024-01-20   Blok A      Joko             1300               8
3 2024-01-21   Blok C    Slamet              900               1
4 2024-01-21   Blok B      Budi             1150               4

In [21]:
# Calculate the salary for each harvester based on the harvest amount. (manipulation)

# 1. calculate total panen
df['Net_Weight_kg'] = df['Total_Weight_kg'] - (df['Rotten_Bunches'] * 5)

# 2. calculate salay for each harvester
df['Wages_IDR'] = 200 * df['Net_Weight_kg']

# change data type
df['Wages_IDR'] = df['Wages_IDR'].round(0).astype(int)

sum_upah = df.groupby('Harvester', observed=True)['Wages_IDR'].sum()
sum_upah

# Jika kamu ingin memastikan tidak ada nilai upah yang negatif always 0
# df['Wages_IDR'] = (200 * df['Net_Weight_kg']).clip(lower=0)

Harvester
Budi       655000
Joko       499000
Slamet     347000
Unknown    215000
Name: Wages_IDR, dtype: int64

## tambahan aja

In [9]:
import pandas as pd
import numpy as np

# Bikin data berantakan buat latihan
data = {
    'ID': [1, 2, np.nan, 4],
    'Nama': ['Andi', 'Budi', 'Caca', 'Dedi'],
    'Departemen': ['HR', np.nan, 'IT', 'IT'],
    'Gaji': [5000000, 6000000, np.nan, 5500000],
    'Kota': ['Jakarta', 'Bandung', 'Jakarta', np.nan]
}
df_challenge = pd.DataFrame(data)
df_challenge.to_csv('employee_data.csv', index=False)

print("File 'employee_data.csv' sudah siap dihajar!")

File 'employee_data.csv' sudah siap dihajar!

In [10]:
dafe = pd.read_csv('employee_data.csv')
print(dafe)
dafe.info()

    ID  Nama Departemen       Gaji     Kota
0  1.0  Andi         HR  5000000.0  Jakarta
1  2.0  Budi        NaN  6000000.0  Bandung
2  NaN  Caca         IT        NaN  Jakarta
3  4.0  Dedi         IT  5500000.0      NaN
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          3 non-null      float64
 1   Nama        4 non-null      object
 2   Departemen  3 non-null      object
 3   Gaji        3 non-null      float64
 4   Kota        3 non-null      object
dtypes: float64(2), object(3)
memory usage: 292.0+ bytes

In [11]:
dafe['Nama'].unique()

array(['Andi', 'Budi', 'Caca', 'Dedi'], dtype=object)

In [12]:
for col in dafe.select_dtypes(include=['number']).columns:
    dafe[col] = dafe[col].fillna(0)


for col in dafe.select_dtypes(include=['object']).columns:
    if col != 'Nama':
        dafe[col] = dafe[col].fillna('TIDAK_ADA').astype('category')
    else:
        dafe[col] = dafe[col].fillna('Tanpa Nama') # Tetap object


# 5. Cek Hasil Akhir
print(dafe.info())
print(dafe)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          4 non-null      float64
 1   Nama        4 non-null      object
 2   Departemen  4 non-null      category
 3   Gaji        4 non-null      float64
 4   Kota        4 non-null      category
dtypes: category(2), float64(2), object(1)
memory usage: 500.0+ bytes
None
    ID  Nama Departemen       Gaji       Kota
0  1.0  Andi         HR  5000000.0    Jakarta
1  2.0  Budi  TIDAK_ADA  6000000.0    Bandung
2  0.0  Caca         IT        0.0    Jakarta
3  4.0  Dedi         IT  5500000.0  TIDAK_ADA