# cleaning iranian dataset 10K transaction

In [1]:
import pandas as pd

df = pd.read_csv('archive/trx-10k.csv')

print('========Lima baris pertama==============')
display(df.head())

print('\n----info tipe data----')
print(df.info())

========Lima baris pertama==============

    status                 time card_type     city     amount  id
0  success  2025-09-07 10:48:00      Visa   Tehran  1427657.0  98
1  success  2025-09-20 13:10:00  MastCard   Tehran  1578078.0  52
2     fail  2025-09-29 03:27:00      Visa  Tehran    250000.0  20
3  success  2025-09-15 13:13:00  Discover  Isfahan        0.0  40
4  success  2025-09-11 11:11:00      Visa   Tehran  1782689.0  59

----info tipe data----
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   status     10000 non-null  object
 1   time       10000 non-null  object
 2   card_type  9689 non-null   object
 3   city       9884 non-null   object
 4   amount     10000 non-null  float64
 5   id         10000 non-null  int64
dtypes: float64(1), int64(1), object(4)
memory usage: 468.9+ KB
None

**change data type**

In [2]:
# pakai looping kalau mau hajar semua kolom teks jadi kategori secara otomatis
# Ambil semua kolom yang tipenya object/string, lalu ubah ke category
for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].astype('category')

if 'time' in df.columns:
    df['time'] = pd.to_datetime(df['time'])

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   status     10000 non-null  category
 1   time       10000 non-null  datetime64[ns]
 2   card_type  9689 non-null   category
 3   city       9884 non-null   category
 4   amount     10000 non-null  float64
 5   id         10000 non-null  int64
dtypes: category(3), datetime64[ns](1), float64(1), int64(1)
memory usage: 265.0 KB

**Handling missing values drop with threshold 5%**

In [3]:
# cek missing values semua variable
print(df.isna().sum())

status         0
time           0
card_type    311
city         116
amount         0
id             0
dtype: int64

In [6]:
threshold =  len(df) * 0.05
print(f'jumlah baris', threshold)

cols_to_drop = df.columns[df.isna().sum() <= threshold]
print(f'value kolom yang akan di drop', cols_to_drop)

df.dropna(subset=cols_to_drop, inplace=True)

print(df.isna().sum())

jumlah baris 500.0
value kolom yang akan di drop Index(['status', 'time', 'card_type', 'city', 'amount', 'id'], dtype='object')
status       0
time         0
card_type    0
city         0
amount       0
id           0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9578 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   status     9578 non-null   category
 1   time       9578 non-null   datetime64[ns]
 2   card_type  9578 non-null   category
 3   city       9578 non-null   category
 4   amount     9578 non-null   float64
 5   id         9578 non-null   int64
dtypes: category(3), datetime64[ns](1), float64(1), int64(1)
memory usage: 328.6 KB

In [8]:
display(df.head())

    status                time card_type     city     amount  id
0  success 2025-09-07 10:48:00      Visa   Tehran  1427657.0  98
1  success 2025-09-20 13:10:00  MastCard   Tehran  1578078.0  52
2     fail 2025-09-29 03:27:00      Visa  Tehran    250000.0  20
3  success 2025-09-15 13:13:00  Discover  Isfahan        0.0  40
4  success 2025-09-11 11:11:00      Visa   Tehran  1782689.0  59